name: myqrcode
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  add_2_calendar: ^3.0.1
  flutter_contacts: ^1.1.9+2
  flutter:
    sdk: flutter
  permission_handler: ^12.0.0+1
  qr_code_scanner: ^1.0.1
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
